test/support/test_plumbing.rb
* now it really compares events by contents, not only by count
* broken since @681d863
=> fix assert_events TestPlumbing helper

lib/cqrs.rb
The order of parameters seems to be wrong right now within the `Cqrs` class. 
The data is correct but the names are not.
This is what I get when starting the app:
Where `Pricing::AddItemToBasket` is a command (not a command handler):
And `Pricing::OnAddItemToBasket` is the command handler (not a command):
This PR contains a small fix for that both for `#register_command` and `#register`. :+1: 
Let me know if I got it wrong. Thanks!
=> Fix parameter order.

ecommerce/shipping/.mutant.yml, ecommerce/shipping/Gemfile, ecommerce/shipping/Gemfile.lock, ecommerce/shipping/Makefile, ecommerce/shipping/README.md, ecommerce/shipping/lib/shipping.rb, ecommerce/shipping/lib/shipping/commands/add_item_to_shipment_picking_list.rb, ecommerce/shipping/lib/shipping/commands/remove_item_from_shipment_picking_list.rb, ecommerce/shipping/lib/shipping/events/item_added_to_shipment_picking_list.rb, ecommerce/shipping/lib/shipping/events/item_removed_from_shipment_picking_list.rb, ecommerce/shipping/lib/shipping/services/on_add_item_to_shipment_picking_list.rb, ecommerce/shipping/lib/shipping/services/on_remove_item_from_shipment_picking_list.rb, ecommerce/shipping/lib/shipping/shipment.rb, ecommerce/shipping/test/on_add_item_to_shipment_picking_list_test.rb, ecommerce/shipping/test/on_remove_item_from_shipment_picking_list_test.rb, ecommerce/shipping/test/shipment_test.rb, ecommerce/shipping/test/test_helper.rb, rails_application/lib/configuration.rb
This PR 
- Adds the Shipping module / BC structure / folders and files 
- Implement the orchestration of the `ItemAddedToShipmentPickingList` and `ItemRemovedFromShipmentPickingList` events. 
- These events are the starting point for the following outlined shipping process / flow
- I plan to implement all events outlined in the shipping process above in follow-up PRs
- At this point Shipping BC treas all type of products - physical and digital - the same, what's not ideal because it creates shipments for digital products. The plan is to solve this in a follow-up PR.
=> Adds Shipping BC

ecommerce/pricing/test/pricing_test.rb, infra/lib/infra/types.rb, rails_application/Gemfile.lock
I noticed that there is a bit of inconsistency in the percentage discount ranges.
Please take a look:
https://github.com/RailsEventStore/ecommerce/blob/da19fe55addf24682630497cc1b2dd5ba19f40c4/ecommerce/pricing/lib/pricing/discounts.rb#L7-L12
here we raise the exception if `value > 100` (so it allows to use `100%` discount), but the  `PercentageDiscount` constraining rule had defined `(gt: 0, lt: 100)` - which means that validation would raise error when we set `100%` 🙂 
I hope my insight is correct, but if not feel free to close my PR 😸
=> Unify discount range

rails_application/app/controllers/client_orders_controller.rb, rails_application/app/read_models/client_orders/configuration.rb, rails_application/app/views/application/_top_navigation.html.erb, rails_application/app/views/client_orders/index.html.erb, rails_application/app/views/client_orders/show.html.erb, rails_application/config/routes.rb, rails_application/db/migrate/20220219130650_create_clients.rb, rails_application/db/migrate/20220219162101_create_client_orders.rb, rails_application/db/schema.rb, rails_application/lib/configuration.rb, rails_application/test/client_orders/customer_registered_test.rb, rails_application/test/client_orders/order_cancelled_test.rb, rails_application/test/client_orders/order_expired_test.rb, rails_application/test/client_orders/order_paid_test.rb, rails_application/test/client_orders/order_submitted_test.rb
* Introduced a view that presents orders of selected (mocked-logged in) client under /client path. Since we currently lack authentication, you can "login" as any client and see the orders.
Currently, only orders that are at least submitted are visible to the client. That's because there's no correlation between the client and the draft order.
The next step would be
* adding real authentication and removing the possibility to see other client's orders,
* correlating client with the draft order
=> Client Panel - see my orders

rails_application/app/controllers/products_controller.rb
When posted wrong vat code: NameError (uninitialized constant Invoicing::Product::VatRateNotApplicable)
But still not working because of https://github.com/RailsEventStore/ecommerce/blob/master/rails_application/app/controllers/products_controller.rb#L45 and exception: [Infra::Types::VatRate.new] :code is missing in Hash input
;)
=> fix exception: uninitialized constant

ecommerce/ordering/lib/ordering/order.rb, ecommerce/ordering/test/remove_item_from_basket_test.rb, rails_application/app/controllers/orders_controller.rb
I noticed an issue with removing items with 0 quantity, so I've just tried to fix it.
When a user tried to remove an item with 0 quantity, it would throw an exception:
WDYT? 🙂
=> Do not allow removal of an item if its quantity is zero

rails_application/app/helpers/application_helper.rb
Currently generated path is wrong, it always shows an empty page. It's because the stream name is `Crm::Order$<id>`, not `Orders$<id>`.
Before:
After:
=> Fix path to the Order history path

ecommerce/pricing/lib/pricing/events.rb, ecommerce/pricing/lib/pricing/pricing_catalog.rb, ecommerce/pricing/lib/pricing/product.rb, ecommerce/pricing/lib/pricing/services.rb, ecommerce/pricing/test/future_prices_test.rb, ecommerce/pricing/test/product_test.rb, rails_application/app/controllers/products_controller.rb, rails_application/app/read_models/products/configuration.rb, rails_application/app/read_models/products/refresh_future_prices_calendar.rb, rails_application/app/views/products/_future_price.html.erb, rails_application/db/migrate/20221215214459_rename_future_prices_calendar_future_prices_calendar.rb, rails_application/db/schema.rb, rails_application/scripts/rebuild_prices.rb, rails_application/test/products/update_future_prices_calenar_test.rb
This PR fixes misconception of future_prices column.
- It replaces it with current prices column, from which we take the current price based on time.
- We store now the price `valid_since` attribute  in UTC time
- removed obsolete `FuturePriceSet` event
The adding of new future prices should work correctly now
Planned next steps:
- remove price column from Product read model
- refactor: introduce `PricingCatalog::Entry`
- allow to remove not saved future price entry
- update product with no reload
- make future prices editable
=> Price from prices calendar

ecommerce/authentication/Gemfile.lock, ecommerce/crm/Gemfile.lock, ecommerce/inventory/Gemfile.lock, ecommerce/invoicing/Gemfile.lock, ecommerce/ordering/Gemfile.lock, ecommerce/payments/Gemfile.lock, ecommerce/pricing/Gemfile.lock, ecommerce/processes/Gemfile.lock, ecommerce/product_catalog/Gemfile.lock, ecommerce/shipping/Gemfile.lock, ecommerce/taxes/Gemfile.lock, infra/Gemfile.lock
Combining multiple dependencies PRs into one.
<details>
<summary>Instructions for merging</summary>
* **Use a merge commit**, so that GitHub will mark all original PRs as merged.
* If your repository does not have merge commits enabled, please temporarily enable them in settings. Tick `Allow merge commits` in the repository settings.
* When ready, merge this PR using `Create a merge commit`.
</details>
* Bump activesupport from 7.0.4 to 7.0.4.1 in /ecommerce/pricing (#250) @app/dependabot
* Bump activesupport from 7.0.3.1 to 7.0.4.1 in /ecommerce/inventory (#248) @app/dependabot
* Bump activesupport from 7.0.3 to 7.0.4.1 in /ecommerce/authentication (#247) @app/dependabot
* Bump activesupport from 7.0.3 to 7.0.4.1 in /ecommerce/invoicing (#246) @app/dependabot
* Bump activesupport from …
=> Combined dependencies PR

ecommerce/processes/test/test_helper.rb, rails_application/Gemfile, rails_application/Gemfile.lock, rails_application/app/read_models/client_orders/configuration.rb, rails_application/app/read_models/client_orders/product.rb, rails_application/app/read_models/client_orders/register_lowest_price.rb, rails_application/app/views/client/orders/edit.html.erb, rails_application/db/migrate/20230110235838_add_lowest_recent_price_to_client_order_products.rb, rails_application/db/schema.rb, rails_application/test/client_orders/product_price_changed_test.rb, rails_application/test/integration/client_orders_test.rb
I'm adding here a simple implementation of the feature proposed with https://github.com/RailsEventStore/ecommerce/issues/223.
If any special offer is presented to a consumer, the lowest price in last 30 days should be also presented.
1. In `ecommerce` this should be done at least whenever any price with discount is presented to the client. However, we could simplify this in the first iteration, by always showing this information if there was any price change lately. 
Thus, my idea was to add this information as a simple info icon with details about the lowest price in last 30 days on the `client_orders/edit` page, at the time when customer is making an order.
2. On `client_orders/edit` page we're using the `ClientOrder::Product` read model. So I've decided to add a new column to …
=> Omnibus directive implementation

rails_application/Gemfile, rails_application/Gemfile.lock, rails_application/app/read_models/client_orders/configuration.rb, rails_application/app/read_models/client_orders/product.rb, rails_application/app/read_models/client_orders/register_lowest_price.rb, rails_application/app/read_models/public_offer/configuration.rb, rails_application/app/read_models/public_offer/product.rb, rails_application/app/read_models/public_offer/register_lowest_price.rb, rails_application/app/views/client/orders/edit.html.erb, rails_application/db/migrate/20230128110104_move_lowest_recent_price_to_public_offer.rb, rails_application/db/schema.rb, rails_application/test/client_orders/product_price_changed_test.rb, rails_application/test/integration/client_orders_test.rb, rails_application/test/integration/public_offer_test.rb, rails_application/test/public_offer/product_price_changed_test.rb
As explained in https://github.com/RailsEventStore/ecommerce/issues/268 we want to move the implementation from `ClientOrders` to `PublicOffer`. 
Apart from doing that, I'm also fixing a bug which was happening when no `PriceChanged` events were published in last 30 days and refactoring - removing `timecop` and using `freeze_time` instead.
Visual QA:
=> Move Omnibus directive implementation to PublicOffer logic

ecommerce/ordering/lib/ordering/order.rb
- **Encapsulate state**
- **Refactor**
- **Allowed transitions**
- **Remove empty line**
- **add eql? and hash methods**
- **refactor**
=> introduce state vo

rails_application/app/controllers/supplies_controller.rb, rails_application/app/views/supplies/new.html.erb, rails_application/test/integration/supplies_test.rb
Issue: https://github.com/RailsEventStore/ecommerce/issues/373
This PR adds BE validations for supply product form. This validations checks if the quantity is integer greater than 0 and if not, the proper validation error is rendered.
=> BE validation for supply product

ecommerce/ordering/lib/ordering/order.rb, ecommerce/ordering/test/order_test.rb, ecommerce/ordering/test/submit_order_test.rb, rails_application/app/controllers/client/orders_controller.rb, rails_application/app/controllers/orders_controller.rb, rails_application/test/client_orders/order_cancelled_test.rb, rails_application/test/client_orders/order_paid_test.rb, rails_application/test/client_orders/update_paid_orders_summary_test.rb, rails_application/test/customers/update_paid_orders_summary_test.rb, rails_application/test/integration/client_orders_test.rb, rails_application/test/integration/orders_test.rb, rails_application/test/orders/order_cancelled_test.rb, rails_application/test/orders/order_paid_test.rb
Issue: https://github.com/RailsEventStore/ecommerce/issues/372
https://github.com/user-attachments/assets/a7459837-8c78-42d0-9efc-642edc2eb0b7
=> Prevent empty order submission

rails_application/app/controllers/products_controller.rb, rails_application/app/views/products/new.html.erb, rails_application/test/integration/products_test.rb, rails_application/test/test_helper.rb
Issue: https://github.com/RailsEventStore/ecommerce/issues/391 
I updated the product creation code to accept the VAT rate `code` as a string, aligning it with how VAT rates are created. Additionally, I renamed the attribute in the product form to `vat_rate_code` to better reflect that it represents the VAT rate code, not the entire VAT rate.
=> Change VAT Rate code from integer to string

rails_application/app/controllers/client/orders_controller.rb, rails_application/app/services/client/orders/submit_service.rb, rails_application/test/services/client/orders/submit_service_test.rb
Issue: https://github.com/RailsEventStore/ecommerce/issues/394
Before there was one SubmitService that handled order submissions from both the client and admin sides. Now there are two separate SubmitServices -  one dedicated to handling order submissions from the client side and another for the admin side.
=> Split Orders Submit Service

ecommerce/pricing/lib/pricing/promotions_calendar.rb, rails_application/test/integration/client_orders_test.rb, rails_application/test/integration/orders_test.rb
Issue: https://github.com/RailsEventStore/ecommerce/issues/386 
`include?` cannot be used with time ranges so i used `cover?`.
=> Fix time promotions bug

rails_application/config/application.rb
Before while running `rails c` there was an error `undefined method ``underscore`` for nil (NoMethodError)`.  
It seems like the issue was caused by lack of proper namespacing for the `Application` class.
=> Fix rails c

ecommerce/taxes/.mutant.yml, ecommerce/taxes/lib/taxes.rb, ecommerce/taxes/lib/taxes/commands.rb, ecommerce/taxes/lib/taxes/events.rb, ecommerce/taxes/lib/taxes/services.rb, ecommerce/taxes/lib/taxes/vat_rate_catalog.rb, ecommerce/taxes/test/taxes_test.rb, ecommerce/taxes/test/vat_rate_catalog_test.rb, rails_application/app/controllers/available_vat_rates_controller.rb, rails_application/app/read_models/vat_rates/configuration.rb, rails_application/app/read_models/vat_rates/remove_available_vat_rate.rb, rails_application/app/views/available_vat_rates/index.html.erb, rails_application/config/routes.rb, rails_application/test/integration/available_vat_rates_test.rb
Issue: https://github.com/RailsEventStore/ecommerce/issues/408 
This PR allows admin to delete VAT Rate. 
https://github.com/user-attachments/assets/dc66f2f4-da23-4256-860f-9e2db4ac09aa
=> Allow admin to remove VAT rate

rails_application/app/controllers/shipments_controller.rb, rails_application/app/read_models/shipments/add_item_to_shipment.rb, rails_application/app/read_models/shipments/configuration.rb, rails_application/app/read_models/shipments/remove_item_from_shipment.rb, rails_application/app/views/orders/show.html.erb, rails_application/app/views/shipments/index.html.erb, rails_application/app/views/shipments/show.html.erb, rails_application/config/routes.rb, rails_application/db/migrate/20241017115056_create_shipment_items.rb, rails_application/db/migrate/20241018113912_change_order_uid_to_uuid_in_shipments.rb, rails_application/db/schema.rb, rails_application/test/client_orders/item_removed_from_basket_test.rb, rails_application/test/integration/shipments_test.rb, rails_application/test/orders/broadcast_test.rb, rails_application/test/orders/item_removed_from_basket_test.rb, rails_application/test/orders/order_expired_test.rb, rails_application/test/orders/order_placed_test.rb, rails_application/test/shipments/item_added_to_shipment_test.rb, rails_application/test/shipments/item_removed_from_shipment_test.rb
Issue: https://github.com/RailsEventStore/ecommerce/issues/405
Clicking "Show Shipment" button opens the shipment page where we can see shipment items.
=> Display shipment items on shipment page

rails_application/app/read_models/client_orders/order_handlers.rb, rails_application/app/read_models/client_orders/rendering/edit_order.rb, rails_application/test/client_orders/update_order_total_value_test.rb, rails_application/test/integration/client_orders_test.rb
Issue: https://github.com/RailsEventStore/ecommerce/issues/98
Now as I client I can see estimated final price of an order and discounts I got before I place the order. 
Order without any discounts: 
Order with time promotion and coupon discount: 
https://github.com/user-attachments/assets/020b5939-3dfc-4715-ab9e-230a9d908486
=> Estime final price of an order for a client

ecommerce/pricing/lib/pricing.rb, ecommerce/pricing/lib/pricing/apply_time_promotion.rb, ecommerce/pricing/lib/pricing/commands.rb, ecommerce/pricing/lib/pricing/discounts.rb, ecommerce/pricing/lib/pricing/events.rb, ecommerce/pricing/lib/pricing/offer.rb, ecommerce/pricing/lib/pricing/services.rb, ecommerce/pricing/test/apply_time_promotion_test.rb, ecommerce/pricing/test/discounts_test.rb, ecommerce/pricing/test/pricing_test.rb, ecommerce/pricing/test/promotions_calendar_test.rb, ecommerce/pricing/test/test_helper.rb, ecommerce/pricing/test/time_promotion_test.rb, rails_application/app/read_models/orders/configuration.rb, rails_application/app/read_models/orders/reset_discount.rb, rails_application/app/read_models/orders/reset_time_promotion_discount_value.rb, rails_application/app/read_models/orders/update_discount.rb, rails_application/app/read_models/orders/update_time_promotion_discount_value.rb, rails_application/app/views/orders/show.html.erb, rails_application/db/migrate/20241002130622_rename_happy_hour_value_to_time_promotion_discount_value.rb, rails_application/db/schema.rb, rails_application/test/integration/orders_test.rb, rails_application/test/orders/broadcast_test.rb, rails_application/test/orders/discount_test.rb, rails_application/test/orders/reset_time_promotion_discount_value_test.rb, rails_application/test/orders/update_time_promotion_discount_value_test.rb
Issue: https://github.com/RailsEventStore/ecommerce/issues/407 
Time Promotions are now displayed on order show page. It currently works only on admin side. The client order show page will be adjusted in another PR. 
https://github.com/user-attachments/assets/dcb300e5-7be4-4c54-a525-68189f94ac40
**Combined discounts are displayed correctly as well:**
=> Display time promotion on order page

ecommerce/pricing/lib/pricing.rb, ecommerce/pricing/lib/pricing/apply_time_promotion.rb, ecommerce/pricing/lib/pricing/commands.rb, ecommerce/pricing/lib/pricing/discounts.rb, ecommerce/pricing/lib/pricing/events.rb, ecommerce/pricing/lib/pricing/offer.rb, ecommerce/pricing/lib/pricing/services.rb, ecommerce/pricing/test/apply_time_promotion_test.rb, ecommerce/pricing/test/pricing_test.rb, ecommerce/pricing/test/test_helper.rb, rails_application/app/controllers/orders_controller.rb, rails_application/app/read_models/client_orders/configuration.rb, rails_application/app/read_models/client_orders/order_handlers.rb, rails_application/app/read_models/orders/configuration.rb, rails_application/app/read_models/orders/remove_discount.rb, rails_application/app/read_models/orders/remove_time_promotion_discount.rb, rails_application/app/views/orders/edit.html.erb, rails_application/config/routes.rb, rails_application/test/client_orders/discount_test.rb, rails_application/test/integration/discount_test.rb, rails_application/test/orders/discount_test.rb, rails_application/test/orders/remove_time_promotion_discount_test.rb
I refactored discounts according to what was discussed in this PR: https://github.com/RailsEventStore/ecommerce/pull/409
- renamed all of the places with the `reset_discount` and similar to `remove_discount` because it better reflects what this code does. 
- moved `type` to the `PercentageDiscount`.
=> Refactor discounts

ecommerce/pricing/test/apply_time_promotion_test.rb, ecommerce/pricing/test/pricing_test.rb, rails_application/app/read_models/client_orders/configuration.rb, rails_application/app/read_models/client_orders/order_handlers.rb, rails_application/app/read_models/client_orders/rendering/show_order.rb, rails_application/db/migrate/20241129122521_add_time_promotion_discount_to_client_orders.rb, rails_application/db/schema.rb, rails_application/test/client_orders/discount_test.rb, rails_application/test/client_orders/time_promotion_discount_test.rb, rails_application/test/integration/client_orders_test.rb, rails_application/test/orders/discount_test.rb, rails_application/test/orders/remove_time_promotion_discount_test.rb
Issue: https://github.com/RailsEventStore/ecommerce/issues/410 
Previously, when a client submitted an order and displayed this order, there was no information about the discounts he received. Now, on the client order show page, there is information about the discounts that were applied.
I also refactored some names that had "reset" to "remove", which I had overlooked during this pull request:
https://github.com/RailsEventStore/ecommerce/pull/422
I was thinking about creating another table for discounts, such as `client_orders_discounts`, and storing the discounts there instead of keeping them in the same table as `client_order` as it is now. What do you think about this?
=> Display time promotion on client order page

rails_application/app/controllers/refunds_controller.rb, rails_application/app/read_models/refunds/configuration.rb, rails_application/app/views/orders/show.html.erb, rails_application/app/views/refunds/new.html.erb, rails_application/config/routes.rb, rails_application/db/migrate/20241209100544_create_refunds.rb, rails_application/db/migrate/20241209102208_create_refund_items.rb, rails_application/db/schema.rb, rails_application/lib/configuration.rb, rails_application/test/integration/refunds_test.rb
Issue: #154 
This PR is the first step to allow order refunds. 
- added "Refund" button on the order's show page 
- after clicking this button a form for a new refund is displayed
Right now the form cannot be filled and submitted but I wanted to make sure that I'm heading in the right direction. Let me know what you think. :)
=> Add new refund form and read models

rails_application/app/controllers/application_controller.rb, rails_application/app/javascript/controllers/timezone_controller.js, rails_application/app/read_models/time_promotions/create_time_promotion.rb, rails_application/app/views/layouts/application.html.erb, rails_application/app/views/time_promotions/index.html.erb, rails_application/test/integration/time_promotions_test.rb
Issue: https://github.com/RailsEventStore/ecommerce/issues/397
Fixed an issue where time promotions that ended recently were being applied to new orders. 
https://github.com/user-attachments/assets/b27b6f76-68b8-4cc3-a9da-a35c252a4e54
=> Fix timezone issue

ecommerce/pricing/lib/pricing/events.rb, ecommerce/pricing/lib/pricing/offer.rb, ecommerce/processes/lib/processes/three_plus_one_free.rb, ecommerce/processes/test/test_helper.rb, ecommerce/processes/test/three_plus_one_free_test.rb, infra/lib/infra/types.rb, rails_application/test/client_orders/item_removed_from_basket_test.rb, rails_application/test/orders/broadcast_test.rb, rails_application/test/orders/item_removed_from_basket_test.rb
- **fix ThreePlusOneFree process on adding items**
- **enhance the `given` helper - flatten passed events**
- **fix ThreePlusOneFree process on removing items**
- **Add price to PriceItemRemoved payload**
- **formatting only change**
=> get three plus one free process work without pricing catalog

ecommerce/processes/.mutant.yml, ecommerce/processes/lib/processes/three_plus_one_free.rb, infra/lib/infra/process_manager.rb
- **migrate ThreePlusOneFree to use ProcessManager**
- **we need a fresh initial process state on each PM#call**
- **remove not needed guards; we check them earlier i the act method**
=> refactor three plus one free to use process manager

ecommerce/pricing/lib/pricing/commands.rb, ecommerce/pricing/lib/pricing/discounts.rb, ecommerce/pricing/lib/pricing/events.rb, ecommerce/pricing/lib/pricing/offer.rb, ecommerce/pricing/lib/pricing/services.rb, ecommerce/pricing/test/apply_time_promotion_test.rb, ecommerce/pricing/test/discounts_test.rb, ecommerce/pricing/test/free_products_test.rb, ecommerce/pricing/test/pricing_test.rb, ecommerce/pricing/test/simple_offer_test.rb, ecommerce/pricing/test/test_helper.rb, ecommerce/pricing/test/three_plus_one_test.rb, ecommerce/pricing/test/time_promotion_test.rb, ecommerce/processes/test/three_plus_one_free_test.rb, rails_application/test/client_orders/item_added_to_basket_test.rb, rails_application/test/client_orders/item_removed_from_basket_test.rb, rails_application/test/client_orders/order_expired_test.rb, rails_application/test/orders/broadcast_test.rb, rails_application/test/orders/discount_test.rb, rails_application/test/orders/item_added_to_basket_test.rb, rails_application/test/orders/item_removed_from_basket_test.rb, rails_application/test/orders/order_expired_test.rb, rails_application/test/orders/order_placed_test.rb, rails_application/test/orders/remove_time_promotion_discount_test.rb, rails_application/test/orders/update_order_total_value_test.rb, rails_application/test/orders/update_time_promotion_discount_value_test.rb
- **let time promotion last longer during the test**
- **publish more pricing info in ItemAdded/ItemRemoved event payloads**
- **fix free products test**
- **add more Pricing::Offer tests to extend coverage and kill mutants**
- **kill mutants**
=> change offer calculations
